spring.application.name=agendamentoestetico

# Configuração da URL de conexão com o banco de dados MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/agendamentoestetico

# Nome do usuário do MySQL
spring.datasource.username=root
# Senha do usuário do MySQL
spring.datasource.password=root

# Senha para o token JWT (deve ser mantida em segredo e segura)
api.security.token.secret=gagonaosabecodar
# Configurações do JPA/Hibernate
# Opcional: configuração do Hibernate para gerenciamento de esquema (ex: criar/atualizar)
# spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=create
server.port=8080
#Esse comando força o Spring a fechar a sessão do Hibernate após cada requisição,
#evitando problemas de LazyInitializationException. O que melhora  o desempenho e a segurança da aplicação, 
#garantindo que as sessões sejam gerenciadas de forma eficiente.
spring.jpa.open-in-view=false
spring.jackson.deserialization.fail-on-null-for-primitives=false


# ==================================================
# Configurações de email para Hostinger (SSL)
# ==================================================
spring.mail.host=smtp.hostinger.com
spring.mail.port=465
# ATENÇÃO: Verifique se este é o e-mail correto que você configurou na Hostinger
spring.mail.username=gian@arantesrepresentacoes.com.br
# Referencia a senha da variável de ambiente 'EMAIL_PASSWORD'
spring.mail.password=${EMAIL_PASSWORD}

# Propriedades adicionais para conexão SSL
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.default-encoding=UTF-8

# Em desenvolvimento:
app.frontend.url=http://localhost:8080

# Em produção (quando você subir o sistema), esse valor será alterado:
# app.frontend.url=https://seu-sistema-estetica.com