spring.application.name=agendamentoestetico

# Configuração da URL de conexão com o banco de dados MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/agendamentoestetico

 # Nome do usuário do MySQL
spring.datasource.username=root
# Senha do usuário do MySQL
spring.datasource.password=root

# Exemplo para MySQL 8

# Configurações do JPA/Hibernate
# Opcional: configuração do Hibernate para gerenciamento de esquema (ex: criar/atualizar)
# spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=create
server.port=8080
#Esse comando força o Spring a fechar a sessão do Hibernate após cada requisição,
#evitando problemas de LazyInitializationException. O que melhora  o desempenho e a segurança da aplicação, 
#garantindo que as sessões sejam gerenciadas de forma eficiente.
spring.jpa.open-in-view=false
spring.jackson.deserialization.fail-on-null-for-primitives=false